name: CD

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: deploy
        name: Deploy to dokku
        uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_SSH_KEY }}
          dokku-host: 'nettecamp.janmikes.cz'
          app-name: 'camp-staging'
          git-push-flags: '--force'
